# Generated by Django 4.2.9 on 2024-01-30 18:16

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='menu/')),
                ('image_alt', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('coffee', 'Coffee'), ('pastry', 'Pastry')], default='coffee', max_length=50)),
            ],
        ),
    ]
